### ISSUE TITLE
Create more recent snapshot w/ sats index

### ISSUE THREAD

**Issue by brianorwhatever** [kvnn/OrdServer#11]
I need the full sats index for my use case. March 15 is also very old in ordinals time. I have the index locally, how can I create a snapshot with it?

**Comment by kvnn** [comment]
> I need the full sats index for my use case. March 15 is also very old in ordinals time. I have the index locally, how can I create a snapshot with it?

Hi, you'd need to create an AWS account, set up a new Volume, `rsync` or `scp` the file to the Volume, then create a Snapshot of it.
